apiVersion: apps/v1 
kind: Deployment  # The first two lines just declare what we want to create
metadata:
  name: sample_deployment # Name of deployment
  labels:
    app: nginx
spec: # Specification for deployment
  replicas: 1  # Number of replicas needed
  selector:
    matchLabels:
      app: nginx
  template: # Template for deployment
    metadata:
      labels:
        app: nginx
    spec: # Specification for Pods
      containers:
      - name: nginx # Defining that we need one container inside of the pod
        image: nginx:1.16 # The one container will have nginx image
        ports:
        - containerPort: 8080 # Binding the Pod to port 8080
