apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017  # Default port of Mongo in Docker hub container
        env:  #Environmental Variables
        - name: MONGO_INITDB_ROOT_USERNAME #Referencing username from secret
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD #Referencing password from secret
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
--- # Document seperation between mongo deployment and service deployment
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 #Service Port
      targetPort: 27017 #Container Port

